### ISSUE TITLE
Unable to create cluster

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-webui#19]
I found that recently i was unable to create cluster as the button is missing. See screenshot below:

![screenshot from 2016-05-31 14 47 53](https://cloud.githubusercontent.com/assets/231601/15667214/3fc52ae6-273f-11e6-843a-34701af9bf90.png)

**Comment by iromli** [comment]
Any news on the progress?

**Comment by tecoholic** [comment]
Will be fixed shortly.

**Comment by iromli** [comment]
Thanks @tecoholic
