### ISSUE TITLE
UI improvements for Container View

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-webui#20]
It would be nice if I could view filter on a container type, like LDAP or oxAuth. Also, it would be helpful if there was a display of the total number  of matching entries. Its too hard to count...

![container_view](https://cloud.githubusercontent.com/assets/3717101/15787968/b0be0f54-298a-11e6-8f85-03be1a4c489c.png)

**Comment by iromli** [comment]
@tecoholic To filter container by its type, have a look at https://github.com/GluuFederation/docs-cluster/blob/version_0.5/sources/reference/api/container.md#filter-containers

**Comment by tecoholic** [comment]
![Filtering of containers](https://cloud.githubusercontent.com/assets/383862/15799750/46d249ac-2a84-11e6-993a-033653224ae6.png)

@iromli Thank you for the reference. Here I have implemented a client-side solution.

**Comment by iromli** [comment]
Thanks @tecoholic. Unfortunately, containers only filtered by its type at the moment.

**Comment by tecoholic** [comment]
@iromli I think we need not worry about filtering from the API side. The API consumer should be able to do it on the client side just by requesting the `/containers` and using the properties in the JSON.

**Comment by iromli** [comment]
> The API consumer should be able to do it on the client side just by requesting the /containers and using the properties in the JSON.

Noted.

But I've found that I was unable to do filtering as seen in screenshot below:

![screenshot from 2016-06-15 00 54 28](https://cloud.githubusercontent.com/assets/231601/16053797/7264e2ba-3294-11e6-9ee7-68363b32f981.png)

**Comment by tecoholic** [comment]
This is a  Firefox specific bug found at https://github.com/lorenzofox3/Smart-Table/issues/254
Fix coming.
