### ISSUE TITLE
LDAP server entry 'duplicates' itself

### ISSUE THREAD

**Issue by i-ghost** [GluuFederation/gluu-webui#28]
Version: Gluu Identity Appliance 3.1.0.Final

Hi,

I'm trying to configure Gluu to use an LDAP source. I've used "Add source LDAP server" to add a new server entry on the "Configuration -> Manage Authentication" page, but it's lead to some weirdness.

Here's what my page has ended up looking like:

![gluu](https://user-images.githubusercontent.com/2255046/31317411-a21de12c-ac38-11e7-99a6-aa23e9368e94.png)

So the bottom entry is the one that Gluu ships with, but I haven't explicitly edited the title of it. Instead, any time I update my entry that I've added (the top one), it changes the title of the bottom one. In addition, there doesn't appear to be a way to remove my custom entry or the internal one.

What is the correct way to add an external LDAP authentication source? I've noticed there's also an area to configure LDAP servers in "Configuration -> Cache Refresh". Any hints would be appreciated.

**Comment by mzico** [comment]
Please use our support portal for any kind of assistance regarding Gluu server.
