### ISSUE TITLE
Creat log with equivalent curl commands for write operations

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-webui#4]
It would be really cool if we had a config-history.log file that provided that provided a log of what happened in the web UI, rendered as curl commands. This would enable an admin to use the GUI for configuration, but to look at the log for the equivalent curl commands, possible to use in scripting. The main focus should be on write commands... read commands aren't a big deal.

**Comment by tecoholic** [comment]
Interesting enhancement.

**Comment by tecoholic** [comment]
fixed with 32b3025f2896ef5f429cce0e3b6c26cdde4239cf now a log file is created in the static folder
